name: "Security"

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: [master]

jobs:
  audit:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo install cargo-audit
      - run: cargo audit
